### ISSUE TITLE
The features and docs needing to add After General Availability

### ISSUE THREAD

**Issue by tokers** [apache/apisix-ingress-controller#454]
Now we are so closed to make this project GA, but before that, we still have some jobs to complete, this issue will be used to track the progress and status for publishing the apisix-ingress-controller/1.0, i.e. the first GA release.

## Feature

- [x] Support `ApisixConsumer`, so that Authentication can be done - https://github.com/apache/apisix-ingress-controller/issues/391 - Priority: High
- [x] Observabilities - https://github.com/apache/apisix-helm-chart/issues/76 Priority: High
- [x] Service subset selector - https://github.com/apache/apisix-ingress-controller/issues/441 - Priority: Low
- [x] More and more Ingress annotations support - https://github.com/apache/apisix-ingress-controller/issues/397 - Priority: HIgh
- [x] Headless Service support - https://github.com/apache/apisix-ingress-controller/issues/255 - Priority: Low
- [x] mutual TLS support (downstream, upstream)-  [#205](https://github.com/apache/apisix-ingress-controller/issues/205) Priority: Middle
- [x] UDP support - https://github.com/apache/apisix-ingress-controller/issues/396, https://github.com/apache/apisix-ingress-controller/issues/116 - Priority: Middle

## Chore
 - [x] ApisixClusterConfig status recording [#455](https://github.com/apache/apisix-ingress-controller/issues/455)- Priority: Middle

## Docs
Related issue: https://github.com/apache/apisix-ingress-controller/issues/456
- [x] More and more practices - Priority: Middle
- [ ] Cover most of all scenarios - Priority: Middle
- [x] installation Step by step - Priority: Middle
- [x] Developer Guide - Priority: Middle
- [ ] Optimize examples (need more and more details, like explicit namespace) - Priority: Middle

## Fix

- [x] Status recording failure - https://github.com/apache/apisix-ingress-controller/pull/452
- [x] Leader election optimization - https://github.com/apache/apisix-ingress-controller/issues/449, #448  - Priority: High
- [x] Makefile optimization about gitsha - https://github.com/apache/apisix-ingress-controller/issues/447 - Priority: Low

**Comment by gxthrj** [comment]
Need to add `docs` and `tests` group.

**Comment by tokers** [comment]
> Need to add `docs` and `tests` group.

Just add by yourself :)

**Comment by gxthrj** [comment]
Updated with some issue links.
