### ISSUE TITLE
proposal: Add CRD ApisixPluginConfig support plugin configs

### ISSUE THREAD

**Issue by shelltea** [apache/apisix-ingress-controller#638]
Add a CRD like `ApisixPluginConfig` to support a group of plugin configs, and `ApisixRoute` add a field be associated with it.

If we want to implement this function, we can split the following tasks:

- [x] Add ApisixPluginConfig custom resource. Only need to modify YAML. #694 
- [x] Add ApisixPluginConfig data structures. #694 
- [x] Add client implementation to interact with Apache APISIX. #772 
- [x] Add ApisixPluginConfig translator, it can convert ApisixPluginConfig data structure into APISIX. #815 
- [x] Add ApisixPluginConfig controller loop, It watches the ApisixPluginConfig resource in the Kubernetes cluster and converts it to the ApisixPluginConfig data structure.  #815 
- [x] Add docs to describe it.

**Comment by tao12345666333** [comment]
Add this to v1.3 milestone.

**Comment by tao12345666333** [comment]
Started a discussion on the mailing list https://lists.apache.org/thread.html/r6e989cb7087feff7ab48157d74cf47aab18c3a1cfd32474b0672e63f%40%3Cdev.apisix.apache.org%3E

**Comment by tao12345666333** [comment]
cc @Donghui0

**Comment by neverCase** [comment]
i'm a volunteer

**Comment by gxthrj** [comment]
> i'm a volunteer

Great, assign to you. Look forward.

**Comment by tao12345666333** [comment]
Thanks! @neverCase If you need help, you can ping me at any time.

**Comment by neverCase** [comment]
ok, got it

**Comment by tokers** [comment]
> ok, got it

Welcome to submit your plan to the mail list :).

**Comment by neverCase** [comment]
> > ok, got it
> 
> Welcome to submit your plan to the mail list :).

OK, i will submit my plan later.

**Comment by neverCase** [comment]
I had replied a mail on the apache mail list, but it seems something wrong.
After sending, i can't find my reply on the mail list.

**Comment by neverCase** [comment]
my plan
1. add ApisixPluginConfig in types.go and generated libraries (such as clientset)
2. add ApisixRoute as a group in config
3. add looper for watching specific resources by using clientset (like k8s.io/client-go) and convert it

**Comment by tokers** [comment]
> I had replied a mail on the apache mail list, but it seems something wrong.
> After sending, i can't find my reply on the mail list.
> @tao12345666333 @tokers

You have to subscribe the dev@apisix.apache.org before you send any mails.

**Comment by tokers** [comment]
> my plan
> 
> 1. add ApisixPluginConfig in types.go and generated libraries (such as clientset)
> 2. add ApisixRoute as a group in config
> 3. add looper for watching specific resources by using clientset (like k8s.io/client-go) and convert it

1. Refer to other types (see https://github.com/apache/apisix-ingress-controller/blob/master/pkg/kube/apisix/apis/config/v2beta1/types.go#L30) so that the CRD definition can be generated with the OpenAPIV3Schema.
2. We need to talk about the mutual exclusivity between `pluginConfig` and `plugins` fields. @tao12345666333 @gxthrj @neverCase

**Comment by tao12345666333** [comment]
> Add a CRD like `ApisixPluginConfig` to support a group of plugin configs, and `ApisixRoute` add a field be associated with it.
> 
> If we want to implement this function, we can split the following tasks:
> 
> * [ ]  Add ApisixPluginConfig custom resource. Only need to modify YAML.
> * [ ]  Add ApisixPluginConfig data structures.
> * [ ]  Add client implementation to interact with Apache APISIX.
> * [ ]  Add ApisixPluginConfig translator, it can convert ApisixPluginConfig data structure into APISIX.
> * [ ]  Add ApisixPluginConfig controller loop, It watches the ApisixPluginConfig resource in the Kubernetes cluster and converts it to the ApisixPluginConfig data structure.
> * [ ]  Add docs to describe it.

You can split this function into multiple small tasks to carry out, refer to these tasks I added in the description. @neverCase

**Comment by tao12345666333** [comment]
> I had replied a mail on the apache mail list, but it seems something wrong.
> After sending, i can't find my reply on the mail list.
> @tao12345666333 @tokers

Yes,  you need to subscribe the dev@apisix.apache.org before you send any mails.

**Of course, whether you are discussing in this issue or on the mailing list, it’s okay.**

**Comment by tao12345666333** [comment]
After discussing it with @tokers and @gxthrj . We finally reached an agreement.

We can set the `plugins`  field and `pluginconfig` field in `ApisixRoute` to be mutually exclusive.

This means that the user can only configure one of the `plugins` or `pluginconfig`  in `ApisixRoute`.

**Comment by neverCase** [comment]
ok, i had created ApisixPluginConfig.yaml and add 3 structs `ApisixPluginConfig`, `ApisixPluginConfigSpec`, `ApisixPluginConfigList` in the v2alpha1/types.go.
But i had trouble in making up fields inside `ApisixPluginConfigSpec`, because i can't find any structs could be linked to the `plugin` in types.go.
```sh
// +genclient
// +genclient:nonNamespaced
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +kubebuilder:subresource:status

// ApisixPluginConfig is the Schema for the ApisixPluginConfig resource.
// An ApisixPluginConfig is used to support a group of plugin configs
type ApisixPluginConfig struct {
	metav1.TypeMeta   `json:",inline" yaml:",inline"`
	metav1.ObjectMeta `json:"metadata" yaml:"metadata"`

	// Spec defines the desired state of ApisixPluginConfigSpec.
	Spec   ApisixPluginConfigSpec `json:"spec" yaml:"spec"`
	Status ApisixStatus           `json:"status,omitempty" yaml:"status,omitempty"`
}

// ApisixPluginConfigSpec defines the desired state of ApisixPluginConfigSpec.
type ApisixPluginConfigSpec struct {
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// ApisixPluginConfigList contains a list of ApisixPluginConfig.
type ApisixPluginConfigList struct {
	metav1.TypeMeta `json:",inline" yaml:",inline"`
	metav1.ListMeta `json:"metadata" yaml:"metadata"`
	Items           []ApisixPluginConfig `json:"items,omitempty" yaml:"items,omitempty"`
}

```
could u provide me more details about the plugins
@tao12345666333

**Comment by tao12345666333** [comment]
You can open a PR and submit your current changes directly. 

The PluginConfig document is here https://apisix.apache.org/docs/apisix/architecture-design/plugin-config 

It looks like this:
```go
// ApisixPluginConfigSpec defines the desired state of ApisixPluginConfigSpec.
type ApisixPluginConfigSpec struct {
    Desc   string            `json:"desc,omitempty" yaml:"desc,omitempty"`
    Plugins Plugins // it should be imported from  https://github.com/apache/apisix-ingress-controller/blob/3e9bdbf0cee6d49c8e0db27152d46565df704e8c/pkg/types/apisix/v1/types.go#L158
}
```

**Comment by tao12345666333** [comment]
@neverCase You can use `[]ApisixRouteHTTPPlugin` directly, no need to define the list yourself.

**Comment by neverCase** [comment]
> @neverCase You can use `[]ApisixRouteHTTPPlugin` directly, no need to define the list yourself.

before pr, should i make up the field `validation` in the `ApisixPluginConfig.yaml`

**Comment by tao12345666333** [comment]
You can open a PR and set it as draf status. Related discussions can be held in the PR, which will be more convenient.

**Comment by fengshunli** [comment]
@tao12345666333  init apisix crd

**Comment by shelltea** [comment]
@tao12345666333 Hi, Can this feature be released in version 1.4.0?

**Comment by tao12345666333** [comment]
@shelltea you can check #694 and #689 If @neverCase  has time to complete this feature, we can include it in 1.4.

**Comment by shelltea** [comment]
@tao12345666333   Thanks!
@neverCase   Hi, Do you have time to complete this feature recently? We really need this feature. 😀

**Comment by neverCase** [comment]
@tao12345666333 @shelltea 
 Actually, I have time to fix this, but I need more help.
I'm willing to contribute my codes.

**Comment by tokers** [comment]
> @tao12345666333 @shelltea Actually, I have time to fix this, but I need more help. I'm willing to contribute my codes.

Feel free to paste your questions there :).

**Comment by tao12345666333** [comment]
> Feel free to paste your questions there :).

@neverCase If you need help, please feel free to ping us

**Comment by neverCase** [comment]
👌  i will update today

**Comment by neverCase** [comment]
@tao12345666333 
hi, should I implement the ApisixPluginConfig in the `TranslateContext`
```sh
// TranslateContext contains APISIX resources generated by the translator.
type TranslateContext struct {
	Routes       []*apisix.Route
	StreamRoutes []*apisix.StreamRoute
	Upstreams    []*apisix.Upstream
	upstreamMap  map[string]struct{}
	SSL          []*apisix.Ssl
}
```

**Comment by tao12345666333** [comment]
@neverCase  You can refer to the following PR to split this work. So that others can also develop collaboratively.

* [chore: consumer data structures by tokers · Pull Request #470 · apache/apisix-ingress-controller](https://github.com/apache/apisix-ingress-controller/pull/470)

* [feat: apisixconsumer translator by tokers · Pull Request #474 · apache/apisix-ingress-controller](https://github.com/apache/apisix-ingress-controller/pull/474)

* [feat: consumer controller loop by tao12345666333 · Pull Request #516 · apache/apisix-ingress-controller](https://github.com/apache/apisix-ingress-controller/pull/516)

**Comment by neverCase** [comment]
> @neverCase You can refer to the following PR to split this work. So that others can also develop collaboratively.
> 
> * [chore: consumer data structures by tokers · Pull Request #470 · apache/apisix-ingress-controller](https://github.com/apache/apisix-ingress-controller/pull/470)
> * [feat: apisixconsumer translator by tokers · Pull Request #474 · apache/apisix-ingress-controller](https://github.com/apache/apisix-ingress-controller/pull/474)
> * [feat: consumer controller loop by tao12345666333 · Pull Request #516 · apache/apisix-ingress-controller](https://github.com/apache/apisix-ingress-controller/pull/516)

OK 👌

**Comment by tao12345666333** [comment]
@neverCase I hope you complete the definition of CRD and data type first. eg. #689 or #694

**Comment by neverCase** [comment]
> @neverCase I hope you complete the definition of CRD and data type first. eg. #689 or #694
Thanks, got it.

**Comment by tao12345666333** [comment]
#694 has been merged. 👍 You can do this job @neverCase 

- [ ]  Add client implementation to interact with Apache APISIX.

**Comment by tao12345666333** [comment]
> * [ ] Add client implementation to interact with Apache APISIX.
> * [ ]  Add ApisixPluginConfig translator, it can convert ApisixPluginConfig data structure into APISIX.
> * [ ]  Add ApisixPluginConfig controller loop, It watches the ApisixPluginConfig resource in the Kubernetes cluster and converts it to the ApisixPluginConfig data structure.
> * [ ]  Add docs to describe it.

@shelltea  @fengshunli   If you are interested, you can also choose one of the tasks.

**Comment by shelltea** [comment]
@tao12345666333   I am very interested, but I'm not familiar with go and Kubernetes.

**Comment by neverCase** [comment]
> #694 has been merged. 👍 You can do this job @neverCase
> 
> * [ ]   Add client implementation to interact with Apache APISIX.

@tao12345666333 
Does this task mean that i should implement the webhook and validation?

**Comment by neverCase** [comment]
> * chore: consumer data structures by tokers · Pull Request #470 · apache/apisix-ingress-controller

ok, got it.

**Comment by neverCase** [comment]
> #694 has been merged. 👍 You can do this job @neverCase
> 
> * [ ]   Add client implementation to interact with Apache APISIX.

ok, got it.

**Comment by tao12345666333** [comment]
@neverCase Thanks for your work, if you have time, you can continue the development of follow-up tasks.

**Comment by neverCase** [comment]
> @neverCase Thanks for your work, if you have time, you can continue the development of follow-up tasks.

ok, got it.
I will update it tomorrow.

**Comment by tao12345666333** [comment]
Hi folks, 

The main part of the ApisixPluginConfig function has been implemented, thanks for your hard work  @neverCase , great!

I’m about to initiate a vote for the release of a new version of v1.4. This feature will appear for the first time in v1.4.

**Comment by tao12345666333** [comment]
For this feature, there is one last task left.

- [ ] Add docs to describe it.

Who has time to help with this task?

**Comment by neverCase** [comment]
> [ ] Add docs to describe it.

I think it's my job -,-.

**Comment by tao12345666333** [comment]
Thanks! @neverCase

**Comment by neverCase** [comment]
@tao12345666333 
This issue could be closed.
