### ISSUE TITLE
[DISCUSS] APISIX Ingress's roadmap for 2022

### ISSUE THREAD

**Issue by tao12345666333** [apache/apisix-ingress-controller#891]
hi, folks, here are the goals and roadmap for the Apache APISIX Ingress project this year.

It will mainly include the following three aspects:

* Usability
  - [ ]  redesign documentation
  - [ ]  add more examples
  - [x]  keep updating
  - [ ]  use a uniform CRD APIVersion #707

* Function enhancement
    
    - [ ] full Gateway API support, progress tracking at: #644 
    - [x] enhanced observability (logging https://github.com/apache/apisix-ingress-controller/issues/899 and tracing)
    - [x] improve stability

* Ecological expansion

    - [x] integrate with some CI/CD tools
         - [x] https://github.com/fluxcd/flagger/issues/1074
         - [x]  https://github.com/argoproj/argo-rollouts/pull/2437        
    - [x] integration with some Kubernetes management platforms

**Comment by Belyenochi** [comment]
I observed that APISIX has plans to support XDS to adapt to Servicemesh like istio, whether APISIX-ingress needs to do similar support.

**Comment by tao12345666333** [comment]
@Belyenochi It will be an independent project, APISIX Ingress will not need to be modified
